import "server-only";

export {
  getAnnouncementsPageData,
  getAttendancePageData,
  getDashboardOverviewData,
  getDsrPageData,
  getEmployeesPageData,
  getExpensesPageData,
  getLeaveBalanceData,
  getLeavesPageData,
  getPayrollPageData,
  getProjectsPageData,
  getReportsPageData,
  getSettingsPageData,
  getTasksPageData,
  getRegularizationPageData,
  getAssetsPageData,
  getEmployeeDocumentsData,
  getAllEmployeeDocumentsData,
  getHolidayCalendarData,
  getClientsPageData,
  getEmployeeDetailData,
  getProjectDetailData,
} from "@/features/dashboard/server/read-model";
