"use client";
import { useActionState } from "react";
import { createClient, deleteClient } from "@/features/dashboard/actions/clients";

type Client = { id: string; clientName: string; companyName: string; clientPhone: string; clientEmail: string; country: string; projectName: string; status: string };
export function ClientsPanel({ clients, projects }: { clients: Client[]; projects: Array<{ id: string; name: string }> }) {
  const [createState, createAction, creating] = useActionState(createClient, {});
  const [deleteState, deleteAction, deleting] = useActionState(deleteClient, {});
  return <div className="space-y-5 px-3 py-3 sm:px-7 sm:py-6"><section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-semibold uppercase tracking-[.14em] text-indigo-600">Super Admin</p><h1 className="mt-1 text-2xl font-semibold text-slate-900">Client directory</h1><p className="mt-1 text-sm text-slate-500">Manage client contacts and their linked project.</p></section>
    <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold text-slate-900">Add client</h2><form action={createAction} className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{createState.error ? <p className="sm:col-span-2 xl:col-span-3 text-sm text-rose-600">{createState.error}</p> : null}{createState.success ? <p className="sm:col-span-2 xl:col-span-3 text-sm text-emerald-600">{createState.success}</p> : null}<Field label="Client name *" name="clientName" required/><Field label="Company" name="companyName"/><Field label="Phone" name="clientPhone"/><Field label="Email" name="clientEmail" type="email"/><Field label="Country" name="country"/><label><span className="mb-1 block text-xs font-medium text-slate-700">Linked project *</span><select className="w-full rounded-md border border-slate-300 px-3 py-2.5 text-sm" name="projectId" required><option value="">Select project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button className="rounded-md bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50" disabled={creating} type="submit">{creating ? "Adding…" : "Add client"}</button></form></section>
    <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 px-5 py-4"><h2 className="font-semibold text-slate-900">All clients ({clients.length})</h2></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs text-slate-500"><tr>{["Client", "Contact", "Country", "Project", "Action"].map(h=><th className="px-4 py-3 font-medium" key={h}>{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{clients.map(c=><tr key={c.id}><td className="px-4 py-3 font-semibold text-slate-800">{c.clientName}<p className="font-normal text-slate-500">{c.companyName}</p></td><td className="px-4 py-3 text-slate-600">{c.clientEmail}<p>{c.clientPhone}</p></td><td className="px-4 py-3 text-slate-600">{c.country || "—"}</td><td className="px-4 py-3 text-slate-600">{c.projectName || "—"}</td><td className="px-4 py-3"><form action={deleteAction}><input name="clientId" type="hidden" value={c.id}/><button className="rounded-md border border-rose-200 bg-rose-50 px-3 py-1.5 text-xs font-semibold text-rose-700" disabled={deleting} onClick={e=>{if(!confirm("Delete this client?"))e.preventDefault();}} type="submit">Delete</button></form></td></tr>)}</tbody></table></div>{deleteState.error ? <p className="p-4 text-sm text-rose-600">{deleteState.error}</p> : null}{deleteState.success ? <p className="p-4 text-sm text-emerald-600">{deleteState.success}</p> : null}</section></div>;
}
function Field({ label, name, required = false, type = "text" }: { label: string; name: string; required?: boolean; type?: string }) { return <label><span className="mb-1 block text-xs font-medium text-slate-700">{label}</span><input className="w-full rounded-md border border-slate-300 px-3 py-2.5 text-sm" name={name} required={required} type={type}/></label>; }
